### ISSUE TITLE
move selected dragHandle with arrow key

### ISSUE THREAD

**Issue by masatodejima0413** [masatodejima0413/lines#27]
やりかたがわからん

https://github.com/atlassian/react-beautiful-dnd/issues/40

これ参考になりそうとおもったけどtabIndexが何者なのかようわからん

**Comment by masatodejima0413** [comment]
- [ ] move item handle with arrow key
- [ ]  move set handle with arrow key
- [ ] remove hover when someone action
- [ ] unexpected handle coloring when dragging

**Comment by makotodejima** [comment]
TabIndex 0 がついてるとtab を押した時にfocus がされるようになるんだけど、今やりたいのは arrow key だから、とりあえず tabindex はdefault のままほって置いていいと思う。
（handle には　default で 0 がついてる。）

ref を handle にも当てて、それをkeydown event で移動するコードを書けばいんじゃないかな

**Comment by masatodejima0413** [comment]
それでいけた

**Comment by masatodejima0413** [comment]
keyboardでitemをdndしてるときのitemhandleのaction挙動がまじでわからん
setの時は普通なのに
